### ISSUE TITLE
evaluateOneRoot() is needed

### ISSUE THREAD

**Issue by CedricLeon** [gegelati/gegelati#78]
In order to re-evaluate one precise root, the current way uses `Learn::LearningAgent::makeJob()` and `Learn::LearningAgent::evaluateJob()`. It's pretty complex and not really clean.

A method such as `evaluateOneRoot(TPG::TPGVertex root, Learn::LearningMode mode)` would be very convenient.

**Comment by kdesnos** [comment]
Solved by PR #104
